/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace StorageInterfaceV5 {
  export type TradeStruct = {
    trader: string;
    pairIndex: BigNumberish;
    index: BigNumberish;
    initialPosToken: BigNumberish;
    positionSizeDai: BigNumberish;
    openPrice: BigNumberish;
    buy: boolean;
    leverage: BigNumberish;
    tp: BigNumberish;
    sl: BigNumberish;
  };

  export type TradeStructOutput = [
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    boolean,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    trader: string;
    pairIndex: BigNumber;
    index: BigNumber;
    initialPosToken: BigNumber;
    positionSizeDai: BigNumber;
    openPrice: BigNumber;
    buy: boolean;
    leverage: BigNumber;
    tp: BigNumber;
    sl: BigNumber;
  };

  export type PendingMarketOrderStruct = {
    trade: StorageInterfaceV5.TradeStruct;
    block: BigNumberish;
    wantedPrice: BigNumberish;
    slippageP: BigNumberish;
    spreadReductionP: BigNumberish;
    tokenId: BigNumberish;
  };

  export type PendingMarketOrderStructOutput = [
    StorageInterfaceV5.TradeStructOutput,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    trade: StorageInterfaceV5.TradeStructOutput;
    block: BigNumber;
    wantedPrice: BigNumber;
    slippageP: BigNumber;
    spreadReductionP: BigNumber;
    tokenId: BigNumber;
  };
}

export interface TradingV62Interface extends utils.Interface {
  contractName: "TradingV62";
  functions: {
    "_msgSender()": FunctionFragment;
    "delegatedAction(address,bytes)": FunctionFragment;
    "delegations(address)": FunctionFragment;
    "isDone()": FunctionFragment;
    "isPaused()": FunctionFragment;
    "limitOrdersTimelock()": FunctionFragment;
    "marketOrdersTimeout()": FunctionFragment;
    "maxPosDai()": FunctionFragment;
    "nftRewards()": FunctionFragment;
    "pairInfos()": FunctionFragment;
    "referrals()": FunctionFragment;
    "removeDelegate()": FunctionFragment;
    "setDelegate(address)": FunctionFragment;
    "storageT()": FunctionFragment;
    "setMaxPosDai(uint256)": FunctionFragment;
    "setLimitOrdersTimelock(uint256)": FunctionFragment;
    "setMarketOrdersTimeout(uint256)": FunctionFragment;
    "pause()": FunctionFragment;
    "done()": FunctionFragment;
    "openTrade((address,uint256,uint256,uint256,uint256,uint256,bool,uint256,uint256,uint256),uint8,uint256,uint256,address)": FunctionFragment;
    "closeTradeMarket(uint256,uint256)": FunctionFragment;
    "updateOpenLimitOrder(uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
    "cancelOpenLimitOrder(uint256,uint256)": FunctionFragment;
    "updateTp(uint256,uint256,uint256)": FunctionFragment;
    "updateSl(uint256,uint256,uint256)": FunctionFragment;
    "executeNftOrder(uint8,address,uint256,uint256,uint256,uint256)": FunctionFragment;
    "openTradeMarketTimeout(uint256)": FunctionFragment;
    "closeTradeMarketTimeout(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "_msgSender",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "delegatedAction",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "delegations", values: [string]): string;
  encodeFunctionData(functionFragment: "isDone", values?: undefined): string;
  encodeFunctionData(functionFragment: "isPaused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "limitOrdersTimelock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "marketOrdersTimeout",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "maxPosDai", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nftRewards",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pairInfos", values?: undefined): string;
  encodeFunctionData(functionFragment: "referrals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeDelegate",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setDelegate", values: [string]): string;
  encodeFunctionData(functionFragment: "storageT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setMaxPosDai",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setLimitOrdersTimelock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMarketOrdersTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "done", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "openTrade",
    values: [
      StorageInterfaceV5.TradeStruct,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "closeTradeMarket",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateOpenLimitOrder",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOpenLimitOrder",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTp",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSl",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeNftOrder",
    values: [
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "openTradeMarketTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closeTradeMarketTimeout",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "_msgSender", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "delegatedAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delegations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isDone", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "limitOrdersTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketOrdersTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "maxPosDai", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nftRewards", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pairInfos", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "referrals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeDelegate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDelegate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "storageT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMaxPosDai",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLimitOrdersTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMarketOrdersTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "done", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "openTrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "closeTradeMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOpenLimitOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOpenLimitOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateTp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updateSl", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeNftOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openTradeMarketTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeTradeMarketTimeout",
    data: BytesLike
  ): Result;

  events: {
    "ChainlinkCallbackTimeout(uint256,tuple)": EventFragment;
    "CouldNotCloseTrade(address,uint256,uint256)": EventFragment;
    "Done(bool)": EventFragment;
    "MarketOrderInitiated(uint256,address,uint256,bool)": EventFragment;
    "NftOrderInitiated(uint256,address,address,uint256)": EventFragment;
    "NftOrderSameBlock(address,address,uint256)": EventFragment;
    "NumberUpdated(string,uint256)": EventFragment;
    "OpenLimitCanceled(address,uint256,uint256)": EventFragment;
    "OpenLimitPlaced(address,uint256,uint256)": EventFragment;
    "OpenLimitUpdated(address,uint256,uint256,uint256,uint256,uint256)": EventFragment;
    "Paused(bool)": EventFragment;
    "SlUpdateInitiated(uint256,address,uint256,uint256,uint256)": EventFragment;
    "SlUpdated(address,uint256,uint256,uint256)": EventFragment;
    "TpUpdated(address,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ChainlinkCallbackTimeout"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CouldNotCloseTrade"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Done"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MarketOrderInitiated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NftOrderInitiated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NftOrderSameBlock"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NumberUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OpenLimitCanceled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OpenLimitPlaced"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OpenLimitUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SlUpdateInitiated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SlUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TpUpdated"): EventFragment;
}

export type ChainlinkCallbackTimeoutEvent = TypedEvent<
  [BigNumber, StorageInterfaceV5.PendingMarketOrderStructOutput],
  {
    orderId: BigNumber;
    order: StorageInterfaceV5.PendingMarketOrderStructOutput;
  }
>;

export type ChainlinkCallbackTimeoutEventFilter =
  TypedEventFilter<ChainlinkCallbackTimeoutEvent>;

export type CouldNotCloseTradeEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { trader: string; pairIndex: BigNumber; index: BigNumber }
>;

export type CouldNotCloseTradeEventFilter =
  TypedEventFilter<CouldNotCloseTradeEvent>;

export type DoneEvent = TypedEvent<[boolean], { done: boolean }>;

export type DoneEventFilter = TypedEventFilter<DoneEvent>;

export type MarketOrderInitiatedEvent = TypedEvent<
  [BigNumber, string, BigNumber, boolean],
  { orderId: BigNumber; trader: string; pairIndex: BigNumber; open: boolean }
>;

export type MarketOrderInitiatedEventFilter =
  TypedEventFilter<MarketOrderInitiatedEvent>;

export type NftOrderInitiatedEvent = TypedEvent<
  [BigNumber, string, string, BigNumber],
  {
    orderId: BigNumber;
    nftHolder: string;
    trader: string;
    pairIndex: BigNumber;
  }
>;

export type NftOrderInitiatedEventFilter =
  TypedEventFilter<NftOrderInitiatedEvent>;

export type NftOrderSameBlockEvent = TypedEvent<
  [string, string, BigNumber],
  { nftHolder: string; trader: string; pairIndex: BigNumber }
>;

export type NftOrderSameBlockEventFilter =
  TypedEventFilter<NftOrderSameBlockEvent>;

export type NumberUpdatedEvent = TypedEvent<
  [string, BigNumber],
  { name: string; value: BigNumber }
>;

export type NumberUpdatedEventFilter = TypedEventFilter<NumberUpdatedEvent>;

export type OpenLimitCanceledEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { trader: string; pairIndex: BigNumber; index: BigNumber }
>;

export type OpenLimitCanceledEventFilter =
  TypedEventFilter<OpenLimitCanceledEvent>;

export type OpenLimitPlacedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { trader: string; pairIndex: BigNumber; index: BigNumber }
>;

export type OpenLimitPlacedEventFilter = TypedEventFilter<OpenLimitPlacedEvent>;

export type OpenLimitUpdatedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
  {
    trader: string;
    pairIndex: BigNumber;
    index: BigNumber;
    newPrice: BigNumber;
    newTp: BigNumber;
    newSl: BigNumber;
  }
>;

export type OpenLimitUpdatedEventFilter =
  TypedEventFilter<OpenLimitUpdatedEvent>;

export type PausedEvent = TypedEvent<[boolean], { paused: boolean }>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export type SlUpdateInitiatedEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber, BigNumber],
  {
    orderId: BigNumber;
    trader: string;
    pairIndex: BigNumber;
    index: BigNumber;
    newSl: BigNumber;
  }
>;

export type SlUpdateInitiatedEventFilter =
  TypedEventFilter<SlUpdateInitiatedEvent>;

export type SlUpdatedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  { trader: string; pairIndex: BigNumber; index: BigNumber; newSl: BigNumber }
>;

export type SlUpdatedEventFilter = TypedEventFilter<SlUpdatedEvent>;

export type TpUpdatedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  { trader: string; pairIndex: BigNumber; index: BigNumber; newTp: BigNumber }
>;

export type TpUpdatedEventFilter = TypedEventFilter<TpUpdatedEvent>;

export interface TradingV62 extends BaseContract {
  contractName: "TradingV62";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TradingV62Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _msgSender(overrides?: CallOverrides): Promise<[string]>;

    delegatedAction(
      trader: string,
      call_data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    delegations(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    isDone(overrides?: CallOverrides): Promise<[boolean]>;

    isPaused(overrides?: CallOverrides): Promise<[boolean]>;

    limitOrdersTimelock(overrides?: CallOverrides): Promise<[BigNumber]>;

    marketOrdersTimeout(overrides?: CallOverrides): Promise<[BigNumber]>;

    maxPosDai(overrides?: CallOverrides): Promise<[BigNumber]>;

    nftRewards(overrides?: CallOverrides): Promise<[string]>;

    pairInfos(overrides?: CallOverrides): Promise<[string]>;

    referrals(overrides?: CallOverrides): Promise<[string]>;

    removeDelegate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDelegate(
      delegate: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    storageT(overrides?: CallOverrides): Promise<[string]>;

    setMaxPosDai(
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setLimitOrdersTimelock(
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMarketOrdersTimeout(
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    done(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    openTrade(
      t: StorageInterfaceV5.TradeStruct,
      orderType: BigNumberish,
      spreadReductionId: BigNumberish,
      slippageP: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    closeTradeMarket(
      pairIndex: BigNumberish,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateOpenLimitOrder(
      pairIndex: BigNumberish,
      index: BigNumberish,
      price: BigNumberish,
      tp: BigNumberish,
      sl: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancelOpenLimitOrder(
      pairIndex: BigNumberish,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateTp(
      pairIndex: BigNumberish,
      index: BigNumberish,
      newTp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateSl(
      pairIndex: BigNumberish,
      index: BigNumberish,
      newSl: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeNftOrder(
      orderType: BigNumberish,
      trader: string,
      pairIndex: BigNumberish,
      index: BigNumberish,
      nftId: BigNumberish,
      nftType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    openTradeMarketTimeout(
      _order: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    closeTradeMarketTimeout(
      _order: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  _msgSender(overrides?: CallOverrides): Promise<string>;

  delegatedAction(
    trader: string,
    call_data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  delegations(arg0: string, overrides?: CallOverrides): Promise<string>;

  isDone(overrides?: CallOverrides): Promise<boolean>;

  isPaused(overrides?: CallOverrides): Promise<boolean>;

  limitOrdersTimelock(overrides?: CallOverrides): Promise<BigNumber>;

  marketOrdersTimeout(overrides?: CallOverrides): Promise<BigNumber>;

  maxPosDai(overrides?: CallOverrides): Promise<BigNumber>;

  nftRewards(overrides?: CallOverrides): Promise<string>;

  pairInfos(overrides?: CallOverrides): Promise<string>;

  referrals(overrides?: CallOverrides): Promise<string>;

  removeDelegate(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDelegate(
    delegate: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  storageT(overrides?: CallOverrides): Promise<string>;

  setMaxPosDai(
    value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setLimitOrdersTimelock(
    value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMarketOrdersTimeout(
    value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  done(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  openTrade(
    t: StorageInterfaceV5.TradeStruct,
    orderType: BigNumberish,
    spreadReductionId: BigNumberish,
    slippageP: BigNumberish,
    referrer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  closeTradeMarket(
    pairIndex: BigNumberish,
    index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateOpenLimitOrder(
    pairIndex: BigNumberish,
    index: BigNumberish,
    price: BigNumberish,
    tp: BigNumberish,
    sl: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancelOpenLimitOrder(
    pairIndex: BigNumberish,
    index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateTp(
    pairIndex: BigNumberish,
    index: BigNumberish,
    newTp: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateSl(
    pairIndex: BigNumberish,
    index: BigNumberish,
    newSl: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeNftOrder(
    orderType: BigNumberish,
    trader: string,
    pairIndex: BigNumberish,
    index: BigNumberish,
    nftId: BigNumberish,
    nftType: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  openTradeMarketTimeout(
    _order: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  closeTradeMarketTimeout(
    _order: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    _msgSender(overrides?: CallOverrides): Promise<string>;

    delegatedAction(
      trader: string,
      call_data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    delegations(arg0: string, overrides?: CallOverrides): Promise<string>;

    isDone(overrides?: CallOverrides): Promise<boolean>;

    isPaused(overrides?: CallOverrides): Promise<boolean>;

    limitOrdersTimelock(overrides?: CallOverrides): Promise<BigNumber>;

    marketOrdersTimeout(overrides?: CallOverrides): Promise<BigNumber>;

    maxPosDai(overrides?: CallOverrides): Promise<BigNumber>;

    nftRewards(overrides?: CallOverrides): Promise<string>;

    pairInfos(overrides?: CallOverrides): Promise<string>;

    referrals(overrides?: CallOverrides): Promise<string>;

    removeDelegate(overrides?: CallOverrides): Promise<void>;

    setDelegate(delegate: string, overrides?: CallOverrides): Promise<void>;

    storageT(overrides?: CallOverrides): Promise<string>;

    setMaxPosDai(value: BigNumberish, overrides?: CallOverrides): Promise<void>;

    setLimitOrdersTimelock(
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setMarketOrdersTimeout(
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    pause(overrides?: CallOverrides): Promise<void>;

    done(overrides?: CallOverrides): Promise<void>;

    openTrade(
      t: StorageInterfaceV5.TradeStruct,
      orderType: BigNumberish,
      spreadReductionId: BigNumberish,
      slippageP: BigNumberish,
      referrer: string,
      overrides?: CallOverrides
    ): Promise<void>;

    closeTradeMarket(
      pairIndex: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateOpenLimitOrder(
      pairIndex: BigNumberish,
      index: BigNumberish,
      price: BigNumberish,
      tp: BigNumberish,
      sl: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelOpenLimitOrder(
      pairIndex: BigNumberish,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateTp(
      pairIndex: BigNumberish,
      index: BigNumberish,
      newTp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateSl(
      pairIndex: BigNumberish,
      index: BigNumberish,
      newSl: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    executeNftOrder(
      orderType: BigNumberish,
      trader: string,
      pairIndex: BigNumberish,
      index: BigNumberish,
      nftId: BigNumberish,
      nftType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    openTradeMarketTimeout(
      _order: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    closeTradeMarketTimeout(
      _order: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ChainlinkCallbackTimeout(uint256,tuple)"(
      orderId?: BigNumberish | null,
      order?: null
    ): ChainlinkCallbackTimeoutEventFilter;
    ChainlinkCallbackTimeout(
      orderId?: BigNumberish | null,
      order?: null
    ): ChainlinkCallbackTimeoutEventFilter;

    "CouldNotCloseTrade(address,uint256,uint256)"(
      trader?: string | null,
      pairIndex?: BigNumberish | null,
      index?: null
    ): CouldNotCloseTradeEventFilter;
    CouldNotCloseTrade(
      trader?: string | null,
      pairIndex?: BigNumberish | null,
      index?: null
    ): CouldNotCloseTradeEventFilter;

    "Done(bool)"(done?: null): DoneEventFilter;
    Done(done?: null): DoneEventFilter;

    "MarketOrderInitiated(uint256,address,uint256,bool)"(
      orderId?: BigNumberish | null,
      trader?: string | null,
      pairIndex?: BigNumberish | null,
      open?: null
    ): MarketOrderInitiatedEventFilter;
    MarketOrderInitiated(
      orderId?: BigNumberish | null,
      trader?: string | null,
      pairIndex?: BigNumberish | null,
      open?: null
    ): MarketOrderInitiatedEventFilter;

    "NftOrderInitiated(uint256,address,address,uint256)"(
      orderId?: null,
      nftHolder?: string | null,
      trader?: string | null,
      pairIndex?: BigNumberish | null
    ): NftOrderInitiatedEventFilter;
    NftOrderInitiated(
      orderId?: null,
      nftHolder?: string | null,
      trader?: string | null,
      pairIndex?: BigNumberish | null
    ): NftOrderInitiatedEventFilter;

    "NftOrderSameBlock(address,address,uint256)"(
      nftHolder?: string | null,
      trader?: string | null,
      pairIndex?: BigNumberish | null
    ): NftOrderSameBlockEventFilter;
    NftOrderSameBlock(
      nftHolder?: string | null,
      trader?: string | null,
      pairIndex?: BigNumberish | null
    ): NftOrderSameBlockEventFilter;

    "NumberUpdated(string,uint256)"(
      name?: null,
      value?: null
    ): NumberUpdatedEventFilter;
    NumberUpdated(name?: null, value?: null): NumberUpdatedEventFilter;

    "OpenLimitCanceled(address,uint256,uint256)"(
      trader?: string | null,
      pairIndex?: BigNumberish | null,
      index?: null
    ): OpenLimitCanceledEventFilter;
    OpenLimitCanceled(
      trader?: string | null,
      pairIndex?: BigNumberish | null,
      index?: null
    ): OpenLimitCanceledEventFilter;

    "OpenLimitPlaced(address,uint256,uint256)"(
      trader?: string | null,
      pairIndex?: BigNumberish | null,
      index?: null
    ): OpenLimitPlacedEventFilter;
    OpenLimitPlaced(
      trader?: string | null,
      pairIndex?: BigNumberish | null,
      index?: null
    ): OpenLimitPlacedEventFilter;

    "OpenLimitUpdated(address,uint256,uint256,uint256,uint256,uint256)"(
      trader?: string | null,
      pairIndex?: BigNumberish | null,
      index?: null,
      newPrice?: null,
      newTp?: null,
      newSl?: null
    ): OpenLimitUpdatedEventFilter;
    OpenLimitUpdated(
      trader?: string | null,
      pairIndex?: BigNumberish | null,
      index?: null,
      newPrice?: null,
      newTp?: null,
      newSl?: null
    ): OpenLimitUpdatedEventFilter;

    "Paused(bool)"(paused?: null): PausedEventFilter;
    Paused(paused?: null): PausedEventFilter;

    "SlUpdateInitiated(uint256,address,uint256,uint256,uint256)"(
      orderId?: BigNumberish | null,
      trader?: string | null,
      pairIndex?: BigNumberish | null,
      index?: null,
      newSl?: null
    ): SlUpdateInitiatedEventFilter;
    SlUpdateInitiated(
      orderId?: BigNumberish | null,
      trader?: string | null,
      pairIndex?: BigNumberish | null,
      index?: null,
      newSl?: null
    ): SlUpdateInitiatedEventFilter;

    "SlUpdated(address,uint256,uint256,uint256)"(
      trader?: string | null,
      pairIndex?: BigNumberish | null,
      index?: null,
      newSl?: null
    ): SlUpdatedEventFilter;
    SlUpdated(
      trader?: string | null,
      pairIndex?: BigNumberish | null,
      index?: null,
      newSl?: null
    ): SlUpdatedEventFilter;

    "TpUpdated(address,uint256,uint256,uint256)"(
      trader?: string | null,
      pairIndex?: BigNumberish | null,
      index?: null,
      newTp?: null
    ): TpUpdatedEventFilter;
    TpUpdated(
      trader?: string | null,
      pairIndex?: BigNumberish | null,
      index?: null,
      newTp?: null
    ): TpUpdatedEventFilter;
  };

  estimateGas: {
    _msgSender(overrides?: CallOverrides): Promise<BigNumber>;

    delegatedAction(
      trader: string,
      call_data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    delegations(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    isDone(overrides?: CallOverrides): Promise<BigNumber>;

    isPaused(overrides?: CallOverrides): Promise<BigNumber>;

    limitOrdersTimelock(overrides?: CallOverrides): Promise<BigNumber>;

    marketOrdersTimeout(overrides?: CallOverrides): Promise<BigNumber>;

    maxPosDai(overrides?: CallOverrides): Promise<BigNumber>;

    nftRewards(overrides?: CallOverrides): Promise<BigNumber>;

    pairInfos(overrides?: CallOverrides): Promise<BigNumber>;

    referrals(overrides?: CallOverrides): Promise<BigNumber>;

    removeDelegate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDelegate(
      delegate: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    storageT(overrides?: CallOverrides): Promise<BigNumber>;

    setMaxPosDai(
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setLimitOrdersTimelock(
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMarketOrdersTimeout(
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    done(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    openTrade(
      t: StorageInterfaceV5.TradeStruct,
      orderType: BigNumberish,
      spreadReductionId: BigNumberish,
      slippageP: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    closeTradeMarket(
      pairIndex: BigNumberish,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateOpenLimitOrder(
      pairIndex: BigNumberish,
      index: BigNumberish,
      price: BigNumberish,
      tp: BigNumberish,
      sl: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancelOpenLimitOrder(
      pairIndex: BigNumberish,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateTp(
      pairIndex: BigNumberish,
      index: BigNumberish,
      newTp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateSl(
      pairIndex: BigNumberish,
      index: BigNumberish,
      newSl: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeNftOrder(
      orderType: BigNumberish,
      trader: string,
      pairIndex: BigNumberish,
      index: BigNumberish,
      nftId: BigNumberish,
      nftType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    openTradeMarketTimeout(
      _order: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    closeTradeMarketTimeout(
      _order: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _msgSender(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    delegatedAction(
      trader: string,
      call_data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    delegations(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isDone(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isPaused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    limitOrdersTimelock(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    marketOrdersTimeout(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxPosDai(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nftRewards(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pairInfos(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    referrals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeDelegate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDelegate(
      delegate: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    storageT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setMaxPosDai(
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setLimitOrdersTimelock(
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMarketOrdersTimeout(
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    done(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    openTrade(
      t: StorageInterfaceV5.TradeStruct,
      orderType: BigNumberish,
      spreadReductionId: BigNumberish,
      slippageP: BigNumberish,
      referrer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    closeTradeMarket(
      pairIndex: BigNumberish,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateOpenLimitOrder(
      pairIndex: BigNumberish,
      index: BigNumberish,
      price: BigNumberish,
      tp: BigNumberish,
      sl: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancelOpenLimitOrder(
      pairIndex: BigNumberish,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateTp(
      pairIndex: BigNumberish,
      index: BigNumberish,
      newTp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateSl(
      pairIndex: BigNumberish,
      index: BigNumberish,
      newSl: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeNftOrder(
      orderType: BigNumberish,
      trader: string,
      pairIndex: BigNumberish,
      index: BigNumberish,
      nftId: BigNumberish,
      nftType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    openTradeMarketTimeout(
      _order: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    closeTradeMarketTimeout(
      _order: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
