import { faGithub, faReadme } from '@fortawesome/free-brands-svg-icons';
import {
    faStar as regStar,
    faCheckCircle as regCheckCircle,
    faCopy as regCopy,
} from '@fortawesome/free-regular-svg-icons';
import {
    faStar,
    faCheckCircle,
    faEllipsisH,
    faTimes,
    faUser,
    faPlus,
    faQuestionCircle,
    faCog,
    faChevronDown,
    faChevronUp,
    faChevronLeft,
    faChevronRight,
    faCrown,
    faDice,
    faGasPump,
    faExternalLinkAlt,
    faVolumeUp,
    faVolumeMute,
    faMinus,
    faUnlink,
    faShareSquare,
    faSignOutAlt,
} from '@fortawesome/free-solid-svg-icons';

export default [
    faGithub,
    faReadme,
    regCopy,
    regStar,
    regCheckCircle,
    faStar,
    faCheckCircle,
    faEllipsisH,
    faTimes,
    faUser,
    faPlus,
    faQuestionCircle,
    faCog,
    faChevronDown,
    faChevronUp,
    faChevronLeft,
    faChevronRight,
    faCrown,
    faDice,
    faGasPump,
    faExternalLinkAlt,
    faVolumeUp,
    faVolumeMute,
    faMinus,
    faUnlink,
    faShareSquare,
    faSignOutAlt,
];
